# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    host: localhost
    username: richard
    password: richard
    database: twentyone_dao_development
    reconnect: true
    pool: 5
  metaplex:
    <<: *default
    host: localhost
    username: richard
    password: richard
    database: metaplex
    reconnect: true
    pool: 5
    database_tasks: false

test:
  <<: *default
  database: solsta_test

production:
  primary:
    <<: *default
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    username: <%= ENV['DB_USERNAME_PRIMARY'] %>
    password: <%= ENV['DB_PASSWORD_PRIMARY'] %>
    database: <%= ENV['DB_DATABASE_PRIMARY'] %>
    reconnect: true
    pool: 5
  metaplex:
    <<: *default
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    username: <%= ENV['DB_USERNAME_METAPLEX'] %>
    password: <%= ENV['DB_PASSWORD_METAPLEX'] %>
    database: <%= ENV['DB_DATABASE_METAPLEX'] %>
    reconnect: true
    pool: 5
    database_tasks: false
